# Site 
repository: danielsieff.github.io
favicon: images/profile.jpg

# Content configuration version
version: 2

# Personal info
name: Daniel Sieff
title: Lead Order to Cash Product Manager
email: sieffdaniel@gmail.com
website: https://danielsieff.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  danielsieff
linkedin_username: https://www.linkedin.com/in/daniel-sieff/

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs  
  A strategic, results-driven executive with extensive expertise in the Salesforce ecosystem and a proven track record in leading customer success and product management teams to drive growth, value realization, and customer satisfaction.
  Expert in aligning technology solutions with business objectives across technology, consumer and retail, and telecommunications industries. 
  Recognized for exceptional communication and stakeholder engagement skills, particularly with C-level executives, and a strong ability to lead cross-functional teams toward shared goals.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I created this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    
    layout: list # Type of content section (list/text)
      - layout: left
        title: Bloomberg Industry Group
        link: bloombergindg.com
        # link_text: bloombergindg.com
        sub_title: Lead Product Manager
        caption: September 2023 - Present
        quote: >
          Managing the lead to cash product team, aligning strategic growth, business goals with technical solutions
        description: | # this will include new lines to allow paragraphs
           - Created a cross-business product strategy and roadmap - Defined and maintained the product vision, strategy, and roadmap for Salesforce solutions, ensuring alignment with overall business goals
           - Team Leadership and Cross-Functional Collaboration for 3 product managers, 1 business analyst and 1 analytics analyst
           - Stakeholder Management and Communication Ensure alignment between business goals and Salesforce implementation to maximize ROI and improve user experience.
           - Requirements Gathering and User Story Development  Develop detailed user stories and acceptance criteria that define how features will work and add value to the platform
           - Salesforce Solution Design and Optimization Review and optimize existing Salesforce processes, data models, and configurations to improve efficiency, usability, and alignment with changing business needs.
           - Compliance, Security, and Governance Implement governance frameworks to maintain data integrity, user access controls, and compliance with regulatory requirements
           - Analytics and Performance Monitoring Define and monitor key performance metrics (KPIs) for the Salesforce platform to track user adoption, system performance, and feature utilization.   
    
    layout: list # Type of content section (list/text)
      - layout: left
        title: Next Quarter
        link: nextq.ai
        # link_text: nextq.ai
        sub_title: Chief Customer Success Officer
        caption: September 2021 - September 2023
        quote: >
          Bought onto the executive team to build the global Customer Success function to drive value realization and achievement of business goals and adoption across the customer base.
        description: | # this will include new lines to allow paragraphs
           - Developed and expanded the Customer Success team to five team members.
           - Defined customer value realization model to align technology-related KPIs to customers' business goals.
           - Developed change management and training guidelines for new customers to enable greater success.
           - Built long-term executive relationships with key strategic customers.
           - Deployed a CSAT survey and built metrics to measure customer satisfaction and ways to improve. 
           - Assisted with prospecting and RFPs to increase account growth and revenue. 
    
    layout: list # Type of content section (list/text)
      - layout: left
        title: Citrix Systems
        link: citrix.com
        # link_text: citrix.com
        sub_title: Executive Customer Successs Manager
        caption: July 2020 - September 2021
        quote: >
          Established Executive Customer Success function across the US to drive customer cloud transformation, value realization, and achievement of business goals and adoption across a small number of Citrix’s largest and most strategic customers.
        description: | # this will include new lines to allow paragraphs
           - Managed relationships with two of Citrix’s largest customers in the Healthcare and Insurance industries.
           - Established customer value realization model to align key technology-related KPIs to customers’ business goals.
           - Developed an extensive Success Plan to measure the impact of the Executive Customer Success function.
           - Successfully built relationships with customer executives to align on business goals and focus Citrix resources on supporting achievement.
           - Quickly built internal executive and account relationships to establish Executive Customer Success as a core part of the account team.
           - Identified new sales and consulting opportunities to grow the customer footprint.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Leeds Metropolitan University
        caption: 1988 - 1992
        sub_title: BSc Information Systems for Business
        quote: >
        description: | # this will include new lines to allow paragraphs
          During my time at Leeds Metropolitan University, I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Certifications
        quote: >
        description: | # this will include new lines to allow paragraphs
           - Certified Scrum Product Owner CSPO
           - Salesforce Administrator
           - Salesforce Sales Cloud Consultant
           - Salesforce Service Cloud Consultant
           - Salesforce AI Specialist
           - Salesforce Business Analyst
           - Salesforce AI Associate
           
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in solutioning some of my other interests and hobbies are:
      - 20 year Volunteer at the Vienna Fire Department
      - Running
      - Soccer coach and ex-certified US soccer referee
      - Race director for the Vienna Turkey Trot

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
